In [10]:
import numpy as np
import matplotlib as mp
r1=int(input("Enter the rows of first matix"))
c1=int(input("Enter the columns of first matrix"))
print("Enter the entries of first row seperated by row")
e1=list(map(int,input().split()))
m1=np.array(e1).reshape(r1,c1)
r2=int(input("Enter the rows of second matix"))
c2=int(input("Enter the columns of second matrix"))
print("Enter the entries of first row seperated by row")
e2=list(map(int,input().split()))
m2=np.array(e2).reshape(r2,c2)
print("First matrix")
print(m1)
print("Second matrix")
print(m2)
print("Dot product of first and second matrices")
d=np.dot(m1,m2)
print(d)
print("Transpose of first matrix")
t=np.transpose(m1)
print(t)
print("Trace of first matrix")
t1=np.trace(m1)
print(t1)
print("Rank of first matrix")
r=np.linalg.matrix_rank(m1)
print(r)
print("Determinant of first matrix")
d1=np.linalg.det(m1)
print(d1)
print("Inverse of first matrix")
i=np.linalg.inv(m1)
print(np.round(i)) 
print("Eigen value of first matrix")
e3=np.linalg.eig(m1)
print(e3)

Enter the rows of first matix 2
Enter the columns of first matrix 2


Enter the entries of first row seperated by row


 1 2 3 4
Enter the rows of second matix 2
Enter the columns of second matrix 2


Enter the entries of first row seperated by row


 1 2 3 4


First matrix
[[1 2]
 [3 4]]
Second matrix
[[1 2]
 [3 4]]
Dot product of first and second matrices
[[ 7 10]
 [15 22]]
Transpose of first matrix
[[1 3]
 [2 4]]
Trace of first matrix
5
Rank of first matrix
2
Determinant of first matrix
-2.0000000000000004
Inverse of first matrix
[[-2.  1.]
 [ 1. -0.]]
Eigen value of first matrix
(array([-0.37228132,  5.37228132]), array([[-0.82456484, -0.41597356],
       [ 0.56576746, -0.90937671]]))
