In [14]:
import numpy as np
x=np.array([3,5,6])
y=np.array([4,5,8])
print("Original numbers:")
print(x)
print(y)
print("comparison_greater")
print(np.greater(x,y))
print("comparison-greater_equal")
print(np.greater_equal(x,y))
print("comparison-less")
print(np.less(x,y))
print("comparison-less_equal")
print(np.less_equal(x,y))

Original numbers:
[3 5 6]
[4 5 8]
comparison_greater
[False False False]
comparison-greater_equal
[False  True False]
comparison-less
[ True False  True]
comparison-less_equal
[ True  True  True]


In [2]:
import numpy as np
array=np.arange(30,71,2,int)
print("Array of all even integers from 30 to 70\n")
print(array)

Array of all even integers from 30 to 70

[30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68 70]


In [3]:
import numpy as np
array=np.identity(3)
print("3X3 identity matrix:\n")
print(array)

3X3 identity matrix:

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [4]:
import numpy as np
array=np.array([[1,2,3],[4,5,6]])
print("sum of all numbers:\n")
print(np.sum(array))
print("sum of column elements:\n")
print(np.sum(array,axis=0))
print("sum of row elements:")
print(np.sum(array,axis=1))

sum of all numbers:

21
sum of column elements:

[5 7 9]
sum of row elements:
[ 6 15]


In [5]:
import numpy as np
array=np.arange(21)
print("Original vector:")
print(array)
print("After changing the sign of the numbers in the range from 9 to 15:")
array[(array >= 9) & (array <= 15)] *= -1
print(array)

Original vector:
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
After changing the sign of the numbers in the range from 9 to 15:
[  0   1   2   3   4   5   6   7   8  -9 -10 -11 -12 -13 -14 -15  16  17
  18  19  20]


In [6]:
import numpy as np
array=np.diag([1,2,3,4,5])
print("5X5 zero matrix with elements on the main diagonal equal to 1,2,3,4,5")
print(array)

5X5 zero matrix with elements on the main diagonal equal to 1,2,3,4,5
[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


In [7]:
import numpy as np
array = np.array([2,4,6,8,10])
print('Array:\n', array)
file = open("file.txt", "w+")
c = str(array)
file.write(c)
file.close()
file = open("file.txt", "r")
c = file.read()
print("Content in file.txt:", c)
file.close()


Array:
 [ 2  4  6  8 10]
Content in file.txt: [ 2  4  6  8 10]


In [8]:
import numpy as np
x=np.array([1,2,3,4])
y=np.array([1,2,3,4])
print("Array 1:")
print(x)
print("Array 2:")
print(y)
print("Array 1 and Array 2 are equal or not:")
a=np.allclose(x,y)
print(a)

Array 1:
[1 2 3 4]
Array 2:
[1 2 3 4]
Array 1 and Array 2 are equal or not:
True


In [9]:
import numpy as np
array = np.arange(16, dtype='int').reshape(-1, 4)
print("Original array:")
print(array)
print("Array after swapping first and last rows:")
array[[0,-1],:]=array[[-1,0],:]
print(array)


Original array:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
Array after swapping first and last rows:
[[12 13 14 15]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [ 0  1  2  3]]


In [12]:
import numpy as np
array1=np.array([1,2,3,4])
array2=np.array([5,6,7,8])
print("Array 1:")
print(array1)
print("Array 2:")
print(array2)
print("Resultant array after multiplication:")
print(np.multiply(array1,array2))

Array 1:
[1 2 3 4]
Array 2:
[5 6 7 8]
Resultant array after multiplication:
[ 5 12 21 32]
